<?php
/**
* subscribersProcessList
*
* @author Ben Byford
* http://www.benbyford.com
*
* @see http://www.processwire.com
*/

class subscribersProcessList extends Process {

    public static function getModuleInfo() {
        return array(
            'title' => 'Subscribers Process List',
            'summary' => 'Pages a list of users with a specific role',
            'version' => 003,
            'requires' => "Subscribers",
            'icon' => 'users',
            'href' => "https://github.com/benbyford/subscribers",
            'permission' => 'subscribers-list',
			'permissions' => array(
				'subscribers-list' => 'View list of users with subscribers role',
				),
        );
    }

    public function ___install() {

    }

    public function execute() {
        // get role from module of default to 'subscribers'
        $role = "subscriber";
        $subscribeModule = $this->modules->getModule('Subscribers');
        if($subscribeModule){
            $role = $subscribeModule->getRole();
        }

        // limit per page
        $limit = 25;

        // get max number of users
        $users = $this->pages->find("template=user,sort=-subscribe_date,roles=$role");
        $count = count($users);

        // get users with a limit
        $users = $this->pages->find("template=user,sort=-subscribe_date,limit=$limit,roles=$role");

        $table = "<table><thead><tr><td>Username</td><td>Name</td><td>Company</td><td>User Role</td><td>Email</td><td>Date subscribed</td><td>Newsletter opt-in</td></tr></thead>";

        $pagination = $users->renderPager();
        $table .= $pagination;

        $userRole = "";
        foreach ($users as $user) {
            $userRole = $role;
            if($user->hasRole("exclusive")){
                $userRole .= ", exclusive";
            }
            $table .= '<tr>';
            $table .= '<td><a href="'. $this->config->urls->admin .'access/roles/edit/?id='. $user->id .'">'. $user->name . '</a></td>';
            $table .= '<td>'. $user->fullname . '</td>';
            $table .= '<td>'. $user->company . '</td>';
            $table .= '<td>'. $userRole . '</td>';
            $table .= '<td><a href="mailto:'.$user->email.'">'. $user->email . '</a></td>';
            $table .= '<td>'. date("d.m.Y", (int)$user->subscribe_date) . '</td>';
            $table .= '<td>'. $user->email_subscribe . '</td>';
            $table .= '</tr>';

            $userRole = "";
        }
        $table .= "</table>";

        $list = "<h2>Users with Role: <b>". $role ."</b> or <b>exclusive</b></h2>";
        $list .= "<h4>Total of <b>". $count ."</b> users</h4>";

        // if bulk clicked then provide commor list of users
        if($this->input->get("bulk")==1){

            $users = $this->pages->find("template=user,sort=-subscribe_date,roles=$role");
            $user_bulk = "<div class='bulk'>";
            foreach ($users as $user) {
                $user_bulk .= $user->email . ", ";
            }
            $user_bulk .= "</div>";
            $list .= $user_bulk;

        }else{
            $list .= "<a class='align_right' href='?bulk=1'>Export list comma delineated</a>";
            $list .= $table;
        }

        return $list;
    }
}
